[workspace]
members = ["core", "runtime", "launcher", "bootstrap"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
sha2 = "0.10"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_System_Memory", "Win32_System_LibraryLoader", "Win32_System_ProcessStatus", "Win32_Security", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_Graphics_Gdi"] }

[profile.release]
lto = true
strip = true
